language: ruby
rvm:
  - "2.0.0"
env: DB=postgres
before_script:
  - psql -c 'create database workoutwars_test' -U postgres
  - psql -c "CREATE USER workoutwars WITH PASSWORD 'uofucs';" -U postgres
  - rake db:create
  - rake db:migrate
script: bundle exec rspec spec